[package]
name = "telegram_auto_poster"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = "0.8"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
